services:

  postgres:
    image: postgres:18
    container_name: account-postgres

    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U account -d account"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  redis:
    image: redis:8
    container_name: account-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: